services:
  server:
    image: hyentaejang/advancedproject
    container_name: codeit_advancedproject_server
    restart: always
    ports:
      - "3001:3001"
    env_file: .env
    networks:
      - network-advancedproject

networks:
  network-advancedproject:
