services:
  server:
    image: hyentaejang/AdvancedProject
    build:
      tags:
        - AdvancedProject
      args:
        - NODE_VERSION=20.18.0
      dockerfile: Dockerfile
      pull: true
      context: .
    container_name: codeit_AdvancedProject_Container
    environment:
      - SERVER_PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB}?schema=public
    networks:
      - network-a

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - network-a

networks:
  network-a:
