name: Deploy Server to EC2

on:
  push:
    branches:
      - deployMain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 이미지 빌드 & DockerHub 에 푸시
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: junejulypark/codi-it-server:latest
      # 2. 배포에 필요한 파일만 복사
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: |
            ./docker-compose.yml
            ./deploy.sh
          target: /home/ubuntu/1-CODI_IT-1

      # 3. .env 파일 자동 생성
      - name: Create .env locally
        run: |
          echo "SERVER_PORT=3001" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: .env
          target: /home/ubuntu/1-CODI_IT-1

      # 4. EC2 접속 해서 배포 스크립트 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/1-CODI_IT-1
            chmod +x deploy.sh
            deploy.sh
